spring:
  datasource:
    url: jdbc:mysql://localhost/sample_db
    username: ${mysql_user}
    password: ${mysql_pass}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.todolistMysql.model
  configuration:
    mapUnderscoreToCamelCase: true
