spring:
  datasource:
    url: jdbc:mysql://localhost/sample_db
    username: xxxx
    password: xxxx

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.todolistMysql.model
  configuration:
    mapUnderscoreToCamelCase: true
